with-expecter: true
filename: "{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/clambin/grafana-exporter/internal/writer:
    interfaces:
      StorageHandler:
