apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: grafana-exporter
  namespace: monitoring
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: exporter
            image: clambin/grafana-exporter:latest
            envFrom:
            - configMapRef:
                name: grafana-exporter
            - secretRef:
                name: grafana-exporter
            args:
            - --url=$(GRAFANA_URL)
            - --api-key=$(GRAFANA_API_KEY)
            - --outdir=/data
            - --dashboard-folders=$(GRAFANA_FOLDERS)
            volumeMounts:
            - name: data
              mountPath: /data
          restartPolicy: Never
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: pvc-grafana-exporter