name: Build

on:
  push:
    branches:
    - master
    - workflows

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@alpha
    with:
      go-version: 1.17

  build:
    needs: test
    uses: clambin/workflows/.github/workflows/build.yaml@alpha
    with:
      go-version: 1.17
      target: grafana-exporter

