name: Build

on:
  push:
    branches:
    - master
    - workflows

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    with:
      go-version: 1.17
  build:
    needs: test
    uses: clambin/workflows/.github/workflows/build.yaml@main
    with:
      go-version: 1.17
      target: grafana-exporter
  docker:
    needs: build
    uses: clambin/workflows/.github/workflows/docker.yaml@main
    with:
      repo: clambin
      target: grafana-exporter
