name: Build

on:
  push:
    branches:
    - master
    - sdk

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@main
    with:
      target: grafana-exporter

