name: Build

on:
  push:
    branches:
    - master
    - workflows

jobs:
  build:
    needs: test
    uses: clambin/workflows/.github/workflows/build.yaml@main
    with:
      go-version: 1.17
      target: grafana-exporter

