name: Build

on:
  push:
    branches:
    - master
    - workflows

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    with:
      go-version: 1.17
  build:
    uses: clambin/workflows/.github/workflows/build.yaml@main
    with:
      go-version: 1.17
      target: grafana-exporter
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: grafana-exporter-linux-arm
          path: ./bld
      - uses: actions/download-artifact@v2
        with:
          name: grafana-exporter-linux-arm64
          path: ./bld
      - uses: actions/download-artifact@v2
        with:
          name: grafana-exporter-linux-amd64
          path: ./bld
      - name: Fix permissions
        run: chmod +x bld/*
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3.6.2
        id: docker_meta
        with:
          images: ghcr.io/clambin/grafana-exporter
          tags: |
            type=sha
            type=semver,pattern={{version}}
      - uses: docker/build-push-action@v2.8.0
        with:
          context: .
          file: ./build/Dockerfile
          platforms: linux/amd64,linux/arm,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            BUILD_VERSION=${{ steps.docker_meta.outputs.version }}
