name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    with:
      go-version: 1.17
  build:
    needs: test
    uses: clambin/workflows/.github/workflows/build.yaml@main
    with:
      go-version: 1.17
      target: grafana-exporter
  docker:
    needs: build
    uses: clambin/workflows/.github/workflows/docker.yaml@main
    with:
      target: grafana-exporter
      repo: clambin
  publish:
    needs: build
    uses:  clambin/workflows/.github/workflows/publish.yaml@main
