name: Test

on:
  push:
    branches-ignore:
      - master
      - helm
  pull_request_target:

jobs:
  analyse:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    with:
      go-version: 1.17
